spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mariadb://localhost:3306/mentoree?charaterEncoding=UTF-8&serverTimezone=UTC
    username: mentoreeAdmin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibername:
        format_sql: true
        use_sql_comments: true
    open-in-view: false


logging.level:
  org.hibernate.SQL: debug